### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by BaixoAlago** [galetskyivan/steamcommunity-mobile-confirmations#33]
Hi! I have a problem.
I'm not finding out why this is giving this error:

> connected
encrypt request
handshake complete
Logged in!
Error: 429
    at SteamcommunityMobileConfirmations.<anonymous> (C:\Users\\Desktop\Nova pasta\bot\Node Bot Escrow\node_modules\steamcommunity-mobile-confirmations\index.js:33:29)
    at Request.self.callback (C:\Users\\Desktop\Nova pasta\bot\Node Bot Escrow\node_modules\steamcommunity-mobile-confirmations\node_modules\request\request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\\Desktop\Nova pasta\bot\Node Bot Escrow\node_modules\steamcommunity-mobile-confirmations\node_modules\request\request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\\Desktop\Nova pasta\bot\Node Bot Escrow\node_modules\steamcommunity-mobile-confirmations\node_modules\request\request.js:962:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by bennetgallein** [comment]
Good Question, I'm getting this every third time trying to get new confirmations.
